[[datasets]]

[[datasets.subsets]]
image_dir = "Z:/kohya_lora/training/7_rikopin1/7_rikopin1"
num_repeats = 10

[general]
enable_bucket = true
resolution = [ 1024, 1024,]
min_bucket_reso = 256
max_bucket_reso = 2048
caption_extension = ".txt"
